lio:
  # Map settings
  map:
    save_map: false
    if_filter: false
    save_map_dir: "map"
    map_name: "map.pcd"
    ds_size: 0.3
    save_interval: 500

  # ROS Topic input
  ros:
    lidar_topic: "/points_raw"
    imu_topic: "/imu_raw"

  # Sensor Configuration
  sensor:
    lidar_type: 5
    blind: 2.0
    maxrange: 150.0
    filter_rate: 3.0
    enable_downsample: true
    voxel_fliter_size: 0.5
    gravity_norm: 9.8
    imu_type: 0
    imu_na: 0.01
    imu_ng: 0.01
    imu_nba: 0.0001
    imu_nbg: 0.0001

  # Extrinsic Parameters
  extrinsic:
    lidar_imu: [0.0, 0.0, 0.28,      # lidar in imu
                1.0, 0.0, 0.0, 
                0.0, 1.0, 0.0, 
                0.0, 0.0, 1.0]
    odom_robo: [0.0, 0, 0, 0, 0.0, 0.0]

  # Vox hash Map
  hash_map:
    hash_capacity: 100000000
    vox_resolution: 0.5

  # Kalman Filter Parameters
  kf:
    kf_type: 0
    kf_max_iterations: 4
    kf_align_gravity: true
    kf_quit_eps: 0.001

  # output
  output:
    robot:  false
    plan_env_world: false
    plan_env_body:  false
    planner: false
    map:    true
    dense:  true
    pub_step: 10
  
  eva:
    timer: true